-- Mini-Phase 11 — AI resume tailoring: the two columns it needs, and nothing else.
--
-- Two separate problems, both of which are schema problems rather than
-- application-logic problems, and both of which have to be solved before a
-- single tailored resume can be written.

-- PROBLEM 1 — resume_documents cannot say what a document IS.
--
-- The candidate's Resumes page lists every resume_documents row for the
-- candidate (client/src/lib/resume.ts listResumes, RLS-scoped), and the
-- submission path resolves "the candidate's resume" as the most recent row
-- (server/applications/resumeGenerator.ts loadBaseResumeDocument, matching
-- the convention greenhouse.ts already used).
--
-- Both of those are correct while every row is something the candidate
-- uploaded. A tailored resume breaks BOTH:
--
--   * it would appear on the Resumes page next to the real uploads, with
--     Extract-facts and Delete affordances that make no sense for a file the
--     candidate never chose;
--   * worse, it becomes the most recent row, so the very next submission
--     resolves it as "the base resume" — and the 'off' setting, whose entire
--     job is to submit the candidate's own file untouched, would silently
--     start submitting a rewritten one.
--
-- So the kind has to be recorded. Default 'uploaded' is what makes this
-- migration safe on existing rows: every row that exists today is an upload,
-- and the default states that rather than inferring it.
alter table public.resume_documents
  add column kind text not null default 'uploaded';

alter table public.resume_documents
  add constraint resume_documents_kind_check
  check (kind in ('uploaded', 'tailored'));

-- Every read of this table is now "the candidate's documents of kind X,
-- newest first" — the Resumes list, the base-resume lookup, and any future
-- per-attempt audit. Matches created_at desc because that is the ordering
-- both existing callers already use.
create index resume_documents_candidate_kind_created_at_idx
  on public.resume_documents (candidate_id, kind, created_at desc);

-- PROBLEM 2 — an attempt cannot name the file it submitted.
--
-- A tailored resume is generated per (candidate, vacancy), so "the resume we
-- sent" is not derivable from the candidate alone after the fact: by the time
-- anyone asks, a newer tailored resume may exist, or the setting may have
-- been changed. The link is recorded on the attempt itself so the audit trail
-- says which exact document went to which employer.
--
-- Nullable on purpose, and null is meaningful rather than merely untidy:
-- NULL means the candidate's own uploaded resume was submitted unmodified
-- (the 'off' path, which creates no new document at all). Existing rows — all
-- of which predate tailoring — are therefore correctly NULL rather than
-- needing a backfill that would have to guess.
--
-- on delete set null: a candidate deleting a tailored resume from their own
-- Resumes page must not fail the delete or erase the attempt record. The
-- attempt keeps its evidence; only the pointer is cleared.
alter table public.application_attempts
  add column resume_document_id uuid references public.resume_documents(id) on delete set null;

comment on column public.application_attempts.resume_document_id is
  'The resume_documents row submitted for this attempt. NULL means the candidate''s own uploaded (kind = uploaded) resume was used unmodified.';

comment on column public.resume_documents.kind is
  'uploaded = a file the candidate provided. tailored = generated by the resume tailoring engine for one vacancy; hidden from the Resumes page and never used as a base resume.';
